spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dojo_jpa?useTimezone=true&serverTimezone=America/Sao_Paulo
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    show-sql: 'true'
